In [2]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
from sklearn import preprocessing
%matplotlib inline


In [30]:
#Завдання №1
#задайте відповідні до вмісту імена колонок датафрейму:
#виведіть описову статистику датасету
#сформуйте масив характеристик X та цільової змінної/класу Y
#виведіть кількість елементів у кожному класі
#поділіть вибірку на навчальну та тестову у співвідношенні 30/70
from sklearn.model_selection import train_test_split

url = "https://archive.ics.uci.edu/ml/machine-learning-databases/00292/Wholesale%20customers%20data.csv"
wholesale_data = pd.read_csv(url)

# Задаємо імена колонок датафрейму
wholesale_data.columns = ['Channel', 'Region', 'Fresh', 'Milk', 'Grocery', 'Frozen', 'Detergents_Paper', 'Delicassen']
wholesale_data.columns


Index(['Channel', 'Region', 'Fresh', 'Milk', 'Grocery', 'Frozen',
       'Detergents_Paper', 'Delicassen'],
      dtype='object')

In [24]:
# Порахуємо кількість даних в кожному класі
wholesale_data['Channel'].value_counts

<bound method IndexOpsMixin.value_counts of 0      2
1      2
2      2
3      1
4      2
      ..
435    1
436    1
437    2
438    1
439    1
Name: Channel, Length: 440, dtype: int64>

In [25]:
#Сформуємо масив ознак без цільової змінної
X_wholesale_data= wholesale_data[['Channel', 'Region', 'Fresh', 'Milk', 'Grocery', 'Frozen', 'Detergents_Paper', 'Delicassen']] .values
X_wholesale_data[0:5]

array([[    2,     3, 12669,  9656,  7561,   214,  2674,  1338],
       [    2,     3,  7057,  9810,  9568,  1762,  3293,  1776],
       [    2,     3,  6353,  8808,  7684,  2405,  3516,  7844],
       [    1,     3, 13265,  1196,  4221,  6404,   507,  1788],
       [    2,     3, 22615,  5410,  7198,  3915,  1777,  5185]],
      dtype=int64)

In [26]:

#Сформуємо вектор цільової змінної
y_wholesale_data = wholesale_data['Channel'].values
y_wholesale_data[0:5]

array([2, 2, 2, 1, 2], dtype=int64)

In [27]:
#Проведемо стандартизацію даних для кращого представлення даних для алгоритму kNN
X_wholesale_data = preprocessing.StandardScaler().fit(X_wholesale_data).transform(X_wholesale_data.astype(float))
X_wholesale_data[0:5]

array([[ 1.44865163,  0.59066829,  0.05293319,  0.52356777, -0.04111489,
        -0.58936716, -0.04356873, -0.06633906],
       [ 1.44865163,  0.59066829, -0.39130197,  0.54445767,  0.17031835,
        -0.27013618,  0.08640684,  0.08915105],
       [ 1.44865163,  0.59066829, -0.44702926,  0.40853771, -0.0281571 ,
        -0.13753572,  0.13323164,  2.24329255],
       [-0.69029709,  0.59066829,  0.10011141, -0.62401993, -0.3929769 ,
         0.6871443 , -0.49858822,  0.09341105],
       [ 1.44865163,  0.59066829,  0.84023948, -0.05239645, -0.07935618,
         0.17385884, -0.23191782,  1.29934689]])

In [32]:
# Поділимо вибірку на навчальну та тестову в пропорції 30/70



X_wholesale_data_train, X_wholesale_data_test, y_wholesale_data_train, y_wholesale_data_test = train_test_split( X_wholesale_data, y_wholesale_data, test_size=0.2, random_state=4)
print ('Навчальна вибірка:', X_wholesale_data_train.shape,  y_wholesale_data.shape)
print ('Тестова вибірка:', X_wholesale_data_test.shape,  y_wholesale_data_test.shape)

Навчальна вибірка: (352, 8) (440,)
Тестова вибірка: (88, 8) (88,)


In [35]:
#Завдання №2
#Проведіть стандартизацію даних
#застосуйте алгоритм kNN для k=3, k=5, використовуючи евклідову метрику та манхеттенську метрику
#порівняйте результати точності для цих моделей
#визначіть оптимальне k за допомогою GridSearchCV
#зробіть висновки
from sklearn.neighbors import KNeighborsClassifier

k = 3
neigh = KNeighborsClassifier(n_neighbors = k, p=1).fit(X_wholesale_data_train,y_wholesale_data_train)
neigh


KNeighborsClassifier(n_neighbors=3, p=1)

In [37]:
k = 5
neigh = KNeighborsClassifier(n_neighbors = k, p=1).fit(X_wholesale_data_train,y_wholesale_data_train)
neigh

KNeighborsClassifier(p=1)

In [36]:
yhat_wholesale_data = neigh.predict(X_wholesale_data_test)
yhat_wholesale_data[0:5]

array([2, 2, 1, 2, 1], dtype=int64)

In [39]:
# оцінимо точність прогнозу

from sklearn import metrics
print("Точність на навчальних даних: ", metrics.accuracy_score(y_wholesale_data_train, neigh.predict(X_wholesale_data_train)))
print("Точність на тестових даних: ", metrics.accuracy_score(y_wholesale_data_test, yhat_wholesale_data))

Точність на навчальних даних:  1.0
Точність на тестових даних:  0.9886363636363636


In [42]:
from sklearn.pipeline import Pipeline
knn_pipe = Pipeline([('scaler', preprocessing.StandardScaler()), ('wholesale_data', Wholesale customers())])
knn_params = {'knn__n_neighbors': range(1, 10)}

SyntaxError: invalid syntax. Perhaps you forgot a comma? (1099795602.py, line 2)

In [13]:
#Завдання №4
#Порівняйте результати класифікації 
#методами kNN та дерева рішень для заданого набору даних
from sklearn.tree import DecisionTreeClassifier

# Навчаємо модель дерева рішень
decision_tree = DecisionTreeClassifier(random_state=42)
decision_tree.fit(X_train_scaled, Y_train)

# Робимо передбачення за допомогою моделі дерева рішень
Y_pred_tree = decision_tree.predict(X_test_scaled)

# Оцінюємо точність моделі дерева рішень
accuracy_tree = accuracy_score(Y_test, Y_pred_tree)
print("\nТочність моделі дерева рішень:", accuracy_tree)
print("\nТочність моделі kNN (k=3, метрика=euclidean):", results[(3, 'euclidean')])
print("Точність моделі kNN (k=3, метрика=manhattan):", results[(3, 'manhattan')])
print("Точність моделі kNN (k=5, метрика=euclidean):", results[(5, 'euclidean')])
print("Точність моделі kNN (k=5, метрика=manhattan):", results[(5, 'manhattan')])



Точність моделі дерева рішень: 0.8484848484848485

Точність моделі kNN (k=3, метрика=euclidean): 0.8787878787878788
Точність моделі kNN (k=3, метрика=manhattan): 0.9090909090909091
Точність моделі kNN (k=5, метрика=euclidean): 0.8863636363636364
Точність моделі kNN (k=5, метрика=manhattan): 0.9090909090909091


In [12]:
#Завдання №6

from sklearn import svm

df_svm= pd.read_csv(url)
df_svm.head()
df_svm.describe()

Channel      Region          Fresh          Milk       Grocery  \
count  440.000000  440.000000     440.000000    440.000000    440.000000   
mean     1.322727    2.543182   12000.297727   5796.265909   7951.277273   
std      0.468052    0.774272   12647.328865   7380.377175   9503.162829   
min      1.000000    1.000000       3.000000     55.000000      3.000000   
25%      1.000000    2.000000    3127.750000   1533.000000   2153.000000   
50%      1.000000    3.000000    8504.000000   3627.000000   4755.500000   
75%      2.000000    3.000000   16933.750000   7190.250000  10655.750000   
max      2.000000    3.000000  112151.000000  73498.000000  92780.000000   

             Frozen  Detergents_Paper    Delicassen  
count    440.000000        440.000000    440.000000  
mean    3071.931818       2881.493182   1524.870455  
std     4854.673333       4767.854448   2820.105937  
min       25.000000          3.000000      3.000000  
25%      742.250000        256.750000    408.250000  
50%     1526.000000        816.500000    965.500000  
75%     3554.250000       3922.000000   1820.250000  
max    60869.000000      40827.000000  47943.000000